name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev
          sudo cmake -S /usr/src/gtest -B /usr/src/gtest/build
          sudo cmake --build /usr/src/gtest/build
          sudo cp /usr/src/gtest/build/lib/*.a /usr/lib

      - name: Build project
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Install binary
        run: sudo cmake --install build

      - name: Run binary
        run: |
          OUT=$(echo -n "Hello" | ascii85 -e)
          echo "OUT=$OUT"

      - name: Run tests
        run: |
          ./build/test
